### ISSUE TITLE
issueベース開発レビュー依頼

### ISSUE THREAD

**Issue by okamoto-yuuki-58a** [okamoto-yuuki-58a/portfolio#4]
■Webアプリの概要
旅行の計画を複数人でシェアできるアプリケーションです。
行きたい場所にピンを立てて共有することで旅行の計画が効率的に行えます。
また、複数の目的地に行くための最適なルートを提案し、ルートの共有が出来ます。
旅行後は写真を投稿し、アルバムを作成できます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：２０時間

■ProjectsのURL
https://github.com/users/okamoto-yuuki-58a/projects/1

■MVPリリースまで
- [x] rails new
- [x] Herokuにデプロイ
- [x] ユーザー登録、ログイン機能
- [x] ユーザー招待機能
- [x] プラン作成機能
- [x] プラン編集機能
- [x] スポット検索機能
- [x] スポット登録機能
- [x] 利用規約
- [x] プライバシーポリシー
- [x] お問い合わせ

■MVP後
- [x] 写真投稿機能
- [x] プランのX投稿機能
- [x] ルート作成機能
- [x] チャット機能
- [x] パスワードリセット機能

■MVPレビュー依頼予定日
予定日：2024年 12月 22日

**Comment by tarakish** [comment]
確認しました👍️
各Issueの内容がなかったので、それぞれのIssueを達成するために必要なタスクを記載するように修正をお願いします！

**Comment by okamoto-yuuki-58a** [comment]
レビューありがとうございました。
指摘いただきました項目につきまして以下の通り修正しましたので、ご確認をお願いいたします。

・各Issueの内容がなかったので、それぞれのIssueを達成するために必要なタスクを記載するように修正をお願いします！
→各issueにタスクを記載しました。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
追加のコメントです。

---

ログイン機能のissueはありますが、ログアウト機能のissueが見受けられなかったのでご確認をお願いします。

**Comment by okamoto-yuuki-58a** [comment]
レビューありがとうございました。
指摘いただきました項目につきまして以下の通り修正しましたので、ご確認をお願いいたします。

・ログイン機能のissueはありますが、ログアウト機能のissueが見受けられなかったのでご確認をお願いします。
→ログアウト機能のissueを追加しました

**Comment by tmtkzk0823** [comment]
確認できました。
LGTMです！
